server:
  port: 9090
spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: jdbc:h2:mem:notificationdb
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true   # to initialize h2 db before the execution of data.sql
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sms-notification-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  sql:
    init:
      mode: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      notificationServiceCircuitBreaker:
        base-config: default
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, metrics, circuitbreakers
  endpoint:
    circuitbreakers:
      enabled: true